[[redirects]]
  from = "/twitch"
  to = "https://twitch.tv/jsdotla"
  status = 302
[[redirects]]
  from = "/rambly"
  to = "https://ramb.ly/js.la"
  status = 302
[[redirects]]
  from = "/slack"
  to = "https://join.slack.com/t/jsla/shared_invite/zt-1nf1yc1f6-ohkEU1TqC3AuHTSiscYHmg"
  status = 302
[[redirects]]
  from = "/lunch"
  to = "https://lunch.js.la"
  status = 302
[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCQc3xx7JEV_gcXjq0SmlCiQ"
  status = 302
[[redirects]]
  from = "/coc"
  to = "/code-of-conduct"
  status = 302
[[redirects]]
  from = "/node"
  to = "https://gumroad.com/l/fullstacknode-full/discord"
  status = 302
[[redirects]]
  from = "/nodeschool"
  to = "https://nodeschool.io/los-angeles"
  status = 302
[[redirects]]
  from = "/forget-frameworks"
  to = "https://forget-frameworks.netlify.app"
[[redirects]]
  from = "/speak"
  to = "https://contribute.js.la/speak"
[[redirects]]
  from = "/cal/*"
  to = "https://lu.ma/jsla-:splat"
  status = 302
  force = true
[[redirects]]
  from = "/mentorship"
  to = "https://juniortosenior.aidaform.com/mentorship"
